"""Aggregate db/categories/*.json into db/all_questions.json and site/data.js."""
import json
import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATEGORIES_DIR = os.path.join(ROOT, "db", "categories")
ALL_JSON_PATH = os.path.join(ROOT, "db", "all_questions.json")
SITE_DATA_PATH = os.path.join(ROOT, "site", "data.js")


def main():
    all_records = []
    for path in sorted(glob.glob(os.path.join(CATEGORIES_DIR, "*.json"))):
        with open(path) as f:
            all_records.extend(json.load(f))

    with open(ALL_JSON_PATH, "w") as f:
        json.dump(all_records, f, indent=2, ensure_ascii=False)
    print(f"Wrote {ALL_JSON_PATH} ({len(all_records)} questions)")

    with open(SITE_DATA_PATH, "w") as f:
        f.write("// Auto-generated by scripts/build_site_data.py — do not edit by hand.\n")
        f.write("const SAT_QUESTIONS = ")
        json.dump(all_records, f, ensure_ascii=False)
        f.write(";\n")
    print(f"Wrote {SITE_DATA_PATH}")


if __name__ == "__main__":
    main()
