"""Build a plain multi-file folder for GitHub Pages (or any static host).

Unlike build_site.py (which inlines all question data into one giant
self-contained HTML file for the Claude Artifact sandbox), this produces:

  site/pages/index.html   the app, small and readable
  site/pages/data.js      const SAT_QUESTIONS = [...] — loaded via <script src>

Push the contents of site/pages/ to the repo (or a subdirectory of it).
"""
import json
import os
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_PATH = os.path.join(ROOT, "site", "index.template.html")
ALL_JSON_PATH = os.path.join(ROOT, "db", "all_questions.json")
IMAGES_SRC_DIR = os.path.join(ROOT, "images")
OUT_DIR = os.path.join(ROOT, "site", "pages")


def main():
    with open(ALL_JSON_PATH) as f:
        questions = json.load(f)

    with open(TEMPLATE_PATH) as f:
        template = f.read()

    # No inline data — data.js (loaded first) defines SAT_QUESTIONS instead.
    html = template.replace(
        '<script id="questions-data" type="application/json">__QUESTIONS_JSON__</script>',
        '<script src="data.js"></script>\n<script id="questions-data" type="application/json">[]</script>',
    )

    if os.path.exists(OUT_DIR):
        shutil.rmtree(OUT_DIR)
    os.makedirs(OUT_DIR)

    with open(os.path.join(OUT_DIR, "index.html"), "w") as f:
        f.write(html)

    with open(os.path.join(OUT_DIR, "data.js"), "w") as f:
        f.write("// Auto-generated by scripts/build_github_pages.py — do not edit by hand.\n")
        f.write("const SAT_QUESTIONS = ")
        json.dump(questions, f, ensure_ascii=False)
        f.write(";\n")

    n_images = 0
    if os.path.isdir(IMAGES_SRC_DIR):
        images_out = os.path.join(OUT_DIR, "images")
        shutil.copytree(IMAGES_SRC_DIR, images_out)
        n_images = sum(len(files) for _, _, files in os.walk(images_out))

    html_size = os.path.getsize(os.path.join(OUT_DIR, "index.html"))
    data_size = os.path.getsize(os.path.join(OUT_DIR, "data.js"))
    print(f"Wrote {OUT_DIR}/index.html ({html_size:,} bytes)")
    print(f"Wrote {OUT_DIR}/data.js ({data_size:,} bytes, {len(questions)} questions)")
    print(f"Copied {n_images} image(s) to {OUT_DIR}/images/")


if __name__ == "__main__":
    main()
