"""Build a plain multi-file folder for GitHub Pages (or any static host).

Unlike build_site.py (which inlines all question data into one giant
self-contained HTML file for the Claude Artifact sandbox), this produces:

  site/pages/index.html   the app, small and readable
  site/pages/data.js      const SAT_QUESTIONS = [...] — loaded via <script src>

Push the contents of site/pages/ to the repo (or a subdirectory of it).
"""
import json
import os
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_PATH = os.path.join(ROOT, "site", "index.template.html")
ALL_JSON_PATH = os.path.join(ROOT, "db", "all_questions.json")
IMAGES_SRC_DIR = os.path.join(ROOT, "images")
OUT_DIR = os.path.join(ROOT, "site", "pages")


def count_files(dir_path):
    if not os.path.isdir(dir_path):
        return 0
    return sum(len(files) for _, _, files in os.walk(dir_path))


def main():
    with open(ALL_JSON_PATH) as f:
        questions = json.load(f)
    if not questions:
        raise SystemExit(
            f"Refusing to build: {ALL_JSON_PATH} has 0 questions. "
            f"That looks like a corrupted/incomplete regeneration, not a real "
            f"deploy — not touching {OUT_DIR} so it keeps whatever it had."
        )

    with open(TEMPLATE_PATH) as f:
        template = f.read()

    # No inline data — data.js (loaded first) defines SAT_QUESTIONS instead.
    html = template.replace(
        '<script id="questions-data" type="application/json">__QUESTIONS_JSON__</script>',
        '<script src="data.js"></script>\n<script id="questions-data" type="application/json">[]</script>',
    )

    # Overwrite index.html/data.js in place rather than rmtree-ing the whole
    # OUT_DIR first — a blanket rmtree used to also wipe images/, and if
    # IMAGES_SRC_DIR ever went missing (it isn't tracked in git, unlike
    # OUT_DIR/images/ itself) there was nothing left to repopulate it with,
    # permanently losing committed deploy images from the working tree.
    os.makedirs(OUT_DIR, exist_ok=True)

    with open(os.path.join(OUT_DIR, "index.html"), "w") as f:
        f.write(html)

    with open(os.path.join(OUT_DIR, "data.js"), "w") as f:
        f.write("// Auto-generated by scripts/build_github_pages.py — do not edit by hand.\n")
        f.write("const SAT_QUESTIONS = ")
        json.dump(questions, f, ensure_ascii=False)
        f.write(";\n")

    # Never let this step shrink what's already deployed: a missing source
    # dir (see git history for why this warning exists) or a partially
    # regenerated one should both leave OUT_DIR/images/ alone rather than
    # silently replacing a complete set with an incomplete one.
    images_out = os.path.join(OUT_DIR, "images")
    existing_count = count_files(images_out)
    src_count = count_files(IMAGES_SRC_DIR)
    if not os.path.isdir(IMAGES_SRC_DIR):
        n_images = existing_count
        print(f"WARNING: {IMAGES_SRC_DIR} not found — left existing {images_out} untouched ({n_images} file(s)), did NOT regenerate it")
    elif src_count < existing_count:
        n_images = existing_count
        print(f"WARNING: {IMAGES_SRC_DIR} has fewer images ({src_count}) than {images_out} already has ({existing_count}) — left it untouched. Delete {images_out} yourself first if this shrink is intentional.")
    else:
        if os.path.exists(images_out):
            shutil.rmtree(images_out)
        shutil.copytree(IMAGES_SRC_DIR, images_out)
        n_images = count_files(images_out)

    html_size = os.path.getsize(os.path.join(OUT_DIR, "index.html"))
    data_size = os.path.getsize(os.path.join(OUT_DIR, "data.js"))
    print(f"Wrote {OUT_DIR}/index.html ({html_size:,} bytes)")
    print(f"Wrote {OUT_DIR}/data.js ({data_size:,} bytes, {len(questions)} questions)")
    print(f"Copied {n_images} image(s) to {OUT_DIR}/images/")


if __name__ == "__main__":
    main()
